<AppWidget>:
    orientation: 'vertical'
    Label:
        id: id_mouse_pos
        text: 'Some very long line which will be cut'
        markup: True
        shorten: True
    BoxLayout:
        id: cerc1
        canvas:
            Color:
                rgb: 1, 0.5, 1
            Line:
                circle: 300, 300, 100
            Color:
                rgb: 1, 0.5, 1
            Line:
                circle: 300, 300, 20
